### ISSUE TITLE
json-decode of 0 is turned into #f

### ISSUE THREAD

**Issue by ekmartin** [joeltg/json.scm#1]
Hi! 
Thanks for creating this.
Found a tiny bug:
```scheme
(json-decode "0")
;; -> #(#f)

(json-decode "[1, 0, 1]")
;; -> #(#(1 #f 1))
```

**Comment by joeltg** [comment]
Should be fixed! Thanks so much for opening this; please find more bugs!

**Comment by ekmartin** [comment]
Great - thanks! We're using it for our final project in 6.945: https://github.com/ekmartin/sprocket
